'use strict';
let tourIndex=-1, tourOrigin='properties', helpReturnFocus=null;
const tourSteps=[
 ['Your workspace','These totals summarize imported properties, saved leads, appraisal context and buyer profiles. They do not measure verified profitable deals.','properties','.metrics'],
 ['Find a property','Use search, county, source and status filters to narrow your queue. Empty counties need imported records; they do not imply no opportunities.','properties','.toolbar'],
 ['Research queue and colors','Select a property. Gray means missing evidence, amber means unresolved concerns, green means ready for final review, and red means entered net economics fail. Color is always paired with text.','properties','#lead-list'],
 ['Why this rating?','Every pursuit rating lists its reasons. Green requires conservative economics, three reviewed recent sales, and your due-diligence checks. It is not a profit guarantee.','properties','#pursuit-detail'],
 ['Photos and map views','Attach a photo you have permission to use. Save confirmed coordinates to open satellite imagery and Street View. Images may be old; the app does not infer current condition.','properties','#visual-panel'],
 ['Property facts and sources','Review parcel, class, size, appraisal and ownership evidence. Appraisal is not a resale estimate. Conflicting owner names need manual review.','properties','#detail .facts'],
 ['Three recent sold comparisons','The panel selects the newest three qualifying closed sales from your imports. Review dates, distances, sizes and source references. No reliable free live sold-price feed is connected.','properties','#comps-panel'],
 ['Model the assignment','Enter ARV and repair ranges, buyer costs and margin, buyer price, seller contract price and your costs. Leave unknowns blank. Save & calculate stores your inputs locally.','properties','#underwriting-form'],
 ['Due diligence and scenario results','Record comp, repair, payoff, title, buyer, contract and disclosure reviews. Inspect conservative/base/optimistic ceilings and your estimated net. Checked boxes are your assertions.','properties','#deal-results'],
 ['Buyer directory','Record actual buyer limits and confirmation dates. Edit or delete profiles. Matching criteria helps build a shortlist; it does not prove funds or a purchase commitment.','buyers','#buyer-form'],
 ['Sources and coverage','Check which counties have local data tools and which need CSV imports. The source links and workflow explain how to gather additional evidence.','sources','#market-coverage'],
 ['Export, phone access and return help','Export visible CSV creates your filtered shortlist. Use Help > Phone access for your private Wi-Fi URL and password. You can restart this tour anytime.','properties','#export']
];
function clearTourHighlight(){document.querySelectorAll('.tour-target').forEach(el=>el.classList.remove('tour-target'));}
function helpDialog(){return document.querySelector('#help-dialog');}
function closeHelp(){clearTourHighlight();helpDialog().close();document.querySelector(`[data-tab="${tourOrigin}"]`)?.click();tourIndex=-1;helpReturnFocus?.focus();}
function showHelp(){helpReturnFocus=document.activeElement;tourOrigin=document.querySelector('[data-tab].active')?.dataset.tab||'properties';tourIndex=-1;clearTourHighlight();const dialog=helpDialog();dialog.innerHTML='<h2 id="help-title">How can we help?</h2><p>Take an optional walkthrough, or learn how to open this app on your phone.</p><div class="help-actions"><button id="start-tour">Start guided tour</button><button id="phone-help" class="secondary">Phone access</button><button id="close-help" class="secondary">Close</button></div><p class="muted">The tour changes views only. It does not save or change your property data.</p>';if(!dialog.open)dialog.showModal();dialog.querySelector('#start-tour').onclick=()=>{tourIndex=0;showTourStep();};dialog.querySelector('#phone-help').onclick=showPhoneHelp;dialog.querySelector('#close-help').onclick=closeHelp;}
function showTourStep(){clearTourHighlight();const [title,text,tab,target]=tourSteps[tourIndex];document.querySelector(`[data-tab="${tab}"]`)?.click();if(tab==='properties'&&!state.selected&&state.visible.length)showDetail(state.visible[0]);const element=document.querySelector(target);if(element){element.classList.add('tour-target');element.scrollIntoView({behavior:'smooth',block:'center'});}const dialog=helpDialog();dialog.innerHTML=`<p class="eyebrow">GUIDED TOUR · ${tourIndex+1} OF ${tourSteps.length}</p><h2 id="help-title">${esc(title)}</h2><p>${esc(text)}</p>${!element?'<p class="muted">This section appears after a property is selected.</p>':''}<div class="help-actions"><button id="tour-back" class="secondary" ${tourIndex===0?'disabled':''}>Back</button><button id="tour-next">${tourIndex===tourSteps.length-1?'Finish':'Next'}</button><button id="close-help" class="secondary">Exit tour</button></div>`;dialog.querySelector('#tour-back').onclick=()=>{tourIndex--;showTourStep();};dialog.querySelector('#tour-next').onclick=()=>{if(tourIndex===tourSteps.length-1)closeHelp();else{tourIndex++;showTourStep();}};dialog.querySelector('#close-help').onclick=closeHelp;dialog.querySelector('#tour-next').focus();}
async function showPhoneHelp(){const dialog=helpDialog();dialog.innerHTML='<h2 id="help-title">Phone access</h2><p>Checking local setup...</p><button id="close-help">Close</button>';dialog.querySelector('#close-help').onclick=closeHelp;try{const data=await api('/api/phone');if(!dialog.open)return;dialog.innerHTML=`<h2 id="help-title">Phone access</h2>${data.enabled?`<ol><li>Keep this computer on and connect your phone to the same trusted Wi-Fi.</li><li>Open <strong>${esc(data.url)}</strong> on your phone.</li><li>This local app uses a self-signed HTTPS certificate. Before continuing, verify the exact address and the SHA-256 fingerprint below against the browser's certificate details.</li><li>Sign in as <strong>${esc(data.username)}</strong> using the password shown below.</li><li>Use your phone browser's Add to Home Screen option for a convenient icon.</li></ol><label>Phone password<input readonly value="${esc(data.password)}" type="password" id="phone-password"></label><button id="reveal-phone" class="secondary">Show password</button><p class="muted">Certificate fingerprint: <code>${esc(data.fingerprint_sha256)}</code><br>Expires: ${esc(data.expires.slice(0,10))}</p><p class="muted">Desktop app must stay running. Wi-Fi isolation or a firewall can block access. No internet port forwarding is configured.</p>`:`<p>Phone access is not enabled${data.error?': '+esc(data.error):'.'}</p><p class="muted">Run scripts/setup_phone.py with this computer's private Wi-Fi IP, restart the app, and allow TCP 8766 only on the private local network. See README for instructions.</p>`}<button id="close-help">Close</button>`;dialog.querySelector('#close-help').onclick=closeHelp;const reveal=dialog.querySelector('#reveal-phone');if(reveal)reveal.onclick=()=>{const field=dialog.querySelector('#phone-password');field.type=field.type==='password'?'text':'password';reveal.textContent=field.type==='password'?'Show password':'Hide password';};}catch(error){dialog.innerHTML=`<h2 id="help-title">Phone access</h2><p>${esc(error.message)}</p><button id="close-help">Close</button>`;dialog.querySelector('#close-help').onclick=closeHelp;}}
document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#help-button').onclick=showHelp;helpDialog().addEventListener('cancel',event=>{event.preventDefault();closeHelp();});});
